//void deplacementPiece(Piece*,char*, char*);
int deplacementPiece(Joueur *,Joueur*,char*,Piece*[]);
//int testPositionInitial(Piece*, char*, Piece*);
int testPositionInitial(Joueur *,char*,Piece*[]);
//int testPositionFinal(Piece*, char*, char*);
int testPositionFinal(char*, Piece*[]);
int isPossible(int,int,Piece*[]);
int solveurAdjacent(int,int,Piece*[]);
int solveurLigneDeVueRectiligne(int,int,Piece*[]);
int solveurLigneDeVueDiagonale(int ,int ,Piece *[]);
int solveurLigneDeVueRectiligneDiagonale(int,int,Piece *[]);
char getReverseCoord(int,char*);
